logging:
#  file:
#    name: /home/wm_user/wm/webapp/logs/wm.log
  level:
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
mybatis:
  type-aliases-package: ai.planit.workmanager.**.dto
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://211.104.145.129:45432/wm_db
#    username: wm_db_user
#    password: alstnelql20!
#  thymeleaf:
#    prefix: classpath:static/
#    suffix: .html
#    cache: false